### ISSUE TITLE
[BUG]: Sensors cannot be created

### ISSUE THREAD

**Issue by chaelli** [CoMPaTech/stromer#32]
### Describe the bug.

Describe the bug.
After installation and adding of my bike I get only one entity (location) and the following logs:
Error adding entities for domain binary_sensor with platform stromer
10:40:05 PM – (ERROR) Binary sensor - message first occurred at 10:40:04 PM and shows up 2 times
Error adding entities for domain sensor with platform stromer
10:40:05 PM – (ERROR) Sensor - message first occurred at 10:40:03 PM and shows up 2 times

the details of the errors are:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'stromer_id'
(for both)

### What version of Home Assistant Core has the issue?

2023.8.3

### What type of installation are you running?

Home Assistant OS

### How did you install the stromer integration

HACS

### Logging

2023-08-29 22:39:56.685 DEBUG (MainThread) [custom_components.stromer.stromer] Stromer attempt: 1/10
2023-08-29 22:39:58.031 DEBUG (MainThread) [custom_components.stromer.stromer] Stromer bike: {'nickname': '', 'bikeid': xxx, 'color': 'orange', 'size': 'sport 20', 'biketype': 'ST2', 'bikemodel': 'ST1 X', 'hardware': 'omniinterfacec'}
2023-08-29 22:39:58.384 DEBUG (MainThread) [custom_components.stromer.stromer] Stromer status: {'trip_distance': 469.7, 'suiversion': '4.4.1.4', 'average_speed_trip': 26.6, 'average_speed_total': 31.1, 'power_on_cycles': 40, 'tntversion': '5.5', 'atmospheric_pressure': 0, 'battery_SOC': 95, 'assistance_level': 0, 'bike_speed': 0.0, 'trip_time': 63513, 'battery_health': 91, 'theft_flag': False, 'motor_temp': 12.0, 'battery_temp': 17.8, 'rcvts': 1693341589, 'average_energy_consumption': 11, 'total_time': 341148, 'total_distance': 2949.9, 'light_on': 0, 'total_energy_consumption': 32701, 'lock_flag': True}
2023-08-29 22:40:02.135 DEBUG (MainThread) [custom_components.stromer.stromer] Stromer position: {'latitude': xxx, 'longitude': xxx, 'altitude': 472.9, 'speed': 0.89, 'timets': 1693341411, 'rcvts': 1693341601}
2023-08-29 22:40:02.135 DEBUG (MainThread) [custom_components.stromer.stromer] Stromer connected!
2023-08-29 22:40:02.135 DEBUG (MainThread) [custom_components.stromer.const] Stromer entry: <homeassistant.config_entries.ConfigEntry object at 0x733ce0f8>
2023-08-29 22:40:02.135 DEBUG (MainThread) [custom_components.stromer.stromer] Stromer attempt: 1/10
2023-08-29 22:40:02.450 DEBUG (MainThread) [custom_components.stromer.stromer] Stromer bike: {'nickname': '', 'bikeid': xxx, 'color': 'orange', 'size': 'sport 20', 'biketype': 'ST2', 'bikemodel': 'ST1 X', 'hardware': 'omniinterfacec'}
2023-08-29 22:40:02.694 DEBUG (MainThread) [custom_components.stromer.stromer] Stromer status: {'trip_distance': 469.7, 'suiversion': '4.4.1.4', 'average_speed_trip': 26.6, 'average_speed_total': 31.1, 'power_on_cycles': 40, 'tntversion': '5.5', 'atmospheric_pressure': 0, 'battery_SOC': 95, 'assistance_level': 0, 'bike_speed': 0.0, 'trip_time': 63513, 'battery_health': 91, 'theft_flag': False, 'motor_temp': 12.0, 'battery_temp': 17.8, 'rcvts': 1693341589, 'average_energy_consumption': 11, 'total_time': 341148, 'total_distance': 2949.9, 'light_on': 0, 'total_energy_consumption': 32701, 'lock_flag': True}
2023-08-29 22:40:03.211 DEBUG (MainThread) [custom_components.stromer.stromer] Stromer position: {'latitude': xxx, 'longitude': xxx, 'altitude': 472.9, 'speed': 0.89, 'timets': 1693341411, 'rcvts': 1693341603}
2023-08-29 22:40:03.211 DEBUG (MainThread) [custom_components.stromer.const] Stromer data [{'nickname': '', 'bikeid': xxx, 'color': 'orange', 'size': 'sport 20', 'biketype': 'ST2', 'bikemodel': 'ST1 X', 'hardware': 'omniinterfacec', 'trip_distance': 469.7, 'suiversion': '4.4.1.4', 'average_speed_trip': 26.6, 'average_speed_total': 31.1, 'power_on_cycles': 40, 'tntversion': '5.5', 'atmospheric_pressure': 0, 'battery_SOC': 95, 'assistance_level': 0, 'bike_speed': 0.0, 'trip_time': 63513, 'battery_health': 91, 'theft_flag': False, 'motor_temp': 12.0, 'battery_temp': 17.8, 'rcvts': 1693341589, 'average_energy_consumption': 11, 'total_time': 341148, 'total_distance': 2949.9, 'light_on': 0, 'total_energy_consumption': 32701, 'lock_flag': True, 'latitude': xxx, 'longitude': xxx, 'altitude': 472.9, 'speed': 0.89, 'timets': 1693341411, 'rcvts_pos': 1693341603}, xxx, ''] updated
2023-08-29 22:40:03.212 DEBUG (MainThread) [custom_components.stromer.const] Finished fetching stromer data in 1.076 seconds (success: True)

### Diagnostics information

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.8.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "armv7l",
    "timezone": "Europe/Zurich",
    "os_name": "Linux",
    "os_version": "6.1.21-v7",
    "supervisor": "2023.08.1",
    "host_os": "Home Assistant OS 10.4",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "shelly": {
      "version": "0.3.5",
      "requirements": [
        "pyShelly==0.3.5",
        "paho-mqtt==1.6.1",
        "websocket-client"
      ]
    },
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "gardena_smart_system": {
      "version": "1.0.0",
      "requirements": [
        "py-smart-gardena==1.3.7"
      ]
    },
    "smartthinq_sensors": {
      "version": "0.31.8",
      "requirements": [
        "pycountry>=20.7.3",
        "xmltodict>=0.12.0",
        "charset_normalizer>=2.0.0"
      ]
    },
    "stromer": {
      "version": "0.2.0",
      "requirements": []
    },
    "smartthinq": {
      "version": "1.0.0",
      "requirements": [
        "wideq>=1.4.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "stromer",
    "name": "Stromer e-bike",
    "codeowners": [
      "@CoMPaTech"
    ],
    "config_flow": true,
    "documentation": "https://github.com/CoMPaTech/stromer",
    "iot_class": "cloud_polling",
    "requirements": [],
    "version": "0.2.0",
    "is_built_in": false
  },
  "data": {
    "bikedata": {
      "nickname": "",
      "bikeid": xxx,
      "color": "orange",
      "size": "sport 20",
      "biketype": "ST2",
      "bikemodel": "ST1 X",
      "hardware": "omniinterfacec",
      "trip_distance": 469.7,
      "suiversion": "4.4.1.4",
      "average_speed_trip": 26.6,
      "average_speed_total": 31.1,
      "power_on_cycles": 40,
      "tntversion": "5.5",
      "atmospheric_pressure": 0,
      "battery_SOC": 95,
      "assistance_level": 0,
      "bike_speed": 0.0,
      "trip_time": 63513,
      "battery_health": 91,
      "theft_flag": false,
      "motor_temp": 12.0,
      "battery_temp": 17.8,
      "rcvts": 1693341589,
      "average_energy_consumption": 11,
      "total_time": 341148,
      "total_distance": 2949.9,
      "light_on": 0,
      "total_energy_consumption": 32701,
      "lock_flag": true,
      "latitude": xxx,
      "longitude": xxx,
      "altitude": 472.9,
      "speed": 0.89,
      "timets": 1693341411,
      "rcvts_pos": 1693341603
    },
    "bike_id": xxx,
    "bike_name": ""
  }
}

**Comment by sammyke007** [comment]
I can confirm the integration stopped working since some weeks...

**Comment by CoMPaTech** [comment]
Please check if 0.2.1 is resolving the issue

**Comment by sammyke007** [comment]
0.2.1 fixed it, tnx!

**Comment by chaelli** [comment]
wow - thanks a lot! solved it for me too
